const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const DATA=path.join(__dirname,'data.json'),OAUTH=path.join(__dirname,'.gmail-oauth.json'),PUB=path.join(__dirname,'public');
const GCLIENT=process.env.GOOGLE_CLIENT_ID||'',GSECRET=process.env.GOOGLE_CLIENT_SECRET||'',BASE=process.env.APP_BASE_URL||'http://localhost:'+(process.env.PORT||8787),REDIRECT=BASE+'/api/gmail/callback';
const load=()=>JSON.parse(fs.readFileSync(DATA,'utf8')),save=x=>fs.writeFileSync(DATA,JSON.stringify(x,null,2));
const oauth=()=>fs.existsSync(OAUTH)?JSON.parse(fs.readFileSync(OAUTH,'utf8')):{},saveOauth=x=>fs.writeFileSync(OAUTH,JSON.stringify(x,null,2),{mode:0o600});
const json=(r,s,x)=>{r.writeHead(s,{'Content-Type':'application/json; charset=utf-8'});r.end(JSON.stringify(x))},body=req=>new Promise((ok,no)=>{let d='';req.on('data',c=>d+=c);req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch(e){no(e)}})});
async function formPost(url,obj){let r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(obj)}),t=await r.json();if(!r.ok)throw Error(t.error_description||t.error||'oauth_error');return t}
async function accessToken(){let o=oauth();if(o.access_token&&o.expires_at>Date.now()+60000)return o.access_token;if(!o.refresh_token)throw Error('gmail_not_connected');let t=await formPost('https://oauth2.googleapis.com/token',{client_id:GCLIENT,client_secret:GSECRET,refresh_token:o.refresh_token,grant_type:'refresh_token'});o={...o,...t,expires_at:Date.now()+t.expires_in*1000};saveOauth(o);return o.access_token}
async function gmail(endpoint,opt={}){let token=await accessToken(),r=await fetch('https://gmail.googleapis.com/gmail/v1/users/me/'+endpoint,{...opt,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json',...(opt.headers||{})}}),t=await r.json();if(!r.ok)throw Error(t.error?.message||'gmail_error');return t}
const b64url=s=>Buffer.from(s).toString('base64').replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
async function sendMail(to,subject,text){let raw=['To: '+to,'Subject: =?UTF-8?B?'+Buffer.from(subject).toString('base64')+'?=','MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','',''+text].join('\r\n');return gmail('messages/send',{method:'POST',body:JSON.stringify({raw:b64url(raw)})})}
function headers(m){return Object.fromEntries((m.payload?.headers||[]).map(h=>[h.name.toLowerCase(),h.value]))}
function decodePart(p){if(p?.body?.data)return Buffer.from(p.body.data.replace(/-/g,'+').replace(/_/g,'/'),'base64').toString('utf8');for(let x of p?.parts||[]){let v=decodePart(x);if(v)return v}return ''}
async function syncGmail(){let st=load(),list=await gmail('messages?q='+encodeURIComponent('RFQ-001 newer_than:90d')+'&maxResults=50'),known=new Set(st.gmailMessages||[]),added=0;for(let it of list.messages||[]){if(known.has(it.id))continue;let m=await gmail('messages/'+it.id+'?format=full'),h=headers(m),from=h.from||'',sub=h.subject||'',txt=decodePart(m.payload)||m.snippet||'';if(/RFQ-001/i.test(sub+' '+txt)){let sup=st.suppliers.find(s=>from.toLowerCase().includes((s.email||'').toLowerCase()));if(sup){sup.status='رد';sup.lastReply=new Date().toISOString();sup.lastSubject=sub}st.activity.unshift({id:Date.now()+Math.random(),time:new Date().toISOString(),type:'gmail_reply',text:'رد جديد: '+(sup?.name||from),messageId:it.id,subject:sub});added++}known.add(it.id)}st.gmailMessages=[...known];save(st);return {added}}
function gate(st,action){let map={followup:'autoFollowup',send:'autoSend',exclude:'autoExclude',award:'autoAward'},key=map[action];if(key&&st.settings?.[key])return true;return st.approvals.some(a=>a.type===action&&a.status==='approved')}

function marketNums(v){return (String(v||'').match(/(?:USD|\\$)\\s*[\\d,.]+|[\\d,.]+\\s*(?:USD|US\\$)/gi)||[]).map(x=>Number(x.replace(/[^\\d.]/g,'').replace(/,(?=\\d{3}\\b)/g,''))).filter(x=>Number.isFinite(x)&&x>0)}
function marketStats(a){a=[...a].sort((x,y)=>x-y);if(!a.length)return null;let q=p=>a[Math.min(a.length-1,Math.floor((a.length-1)*p))];return {low:a[0],median:q(.5),high:a[a.length-1],targetLow:q(.2),targetHigh:q(.45),count:a.length}}
async function googleMarketSources(q){if(!process.env.GOOGLE_CSE_API_KEY||!process.env.GOOGLE_CSE_ID)return [];let u='https://www.googleapis.com/customsearch/v1?key='+encodeURIComponent(process.env.GOOGLE_CSE_API_KEY)+'&cx='+encodeURIComponent(process.env.GOOGLE_CSE_ID)+'&num=10&q='+encodeURIComponent(q);let r=await fetch(u),j=await r.json();if(!r.ok)throw Error(j.error?.message||'market_search_error');return (j.items||[]).map(x=>({type:'Published Price',title:x.title,url:x.link,snippet:x.snippet,prices:marketNums(x.title+' '+x.snippet)}))}
function historicalMarketSources(st,req){return (st.quotes||[]).map(x=>({type:'Historical Price',title:'Internal quote '+x.id,url:null,prices:[x.totalPrice,x.price,x.unitPrice].map(Number).filter(n=>Number.isFinite(n)&&n>0)})).filter(x=>x.prices.length)}
async function marketScan(st,req){let query=[req.title,req.product,req.specifications,req.quantity,req.targetMarkets,'price supplier manufacturer'].filter(Boolean).join(' '),sources=historicalMarketSources(st,req),mode='historical';try{let live=await googleMarketSources(query);if(live.length){sources.push(...live);mode='live+historical'}}catch(e){mode='historical-search-error'}for(let x of req.sourceObservations||[]){let p=marketNums((x.price||'')+' '+(x.note||''));if(p.length)sources.push({type:x.type||'Published Price',title:x.title||'User supplied source',url:x.url||null,prices:p})}let values=sources.flatMap(x=>x.prices||[]),s=marketStats(values),confidence=Math.min(95,Math.round((sources.length>=6?55:sources.length*8)+(values.length>=8?25:values.length*3)+(mode.startsWith('live')?15:0)));return {id:'MS-'+Date.now(),requestId:req.id,createdAt:new Date().toISOString(),query,mode,sourceCount:sources.length,confidence,benchmark:s,classification:{verifiedQuotes:sources.filter(x=>x.type==='Verified Quote').length,publishedPrices:sources.filter(x=>x.type==='Published Price').length,historicalPrices:sources.filter(x=>x.type==='Historical Price').length,aiEstimates:sources.filter(x=>x.type==='AI Estimate').length},sources:sources.slice(0,30),disclaimer:'Indicative benchmark only; published and AI-derived prices are not verified supplier quotations.'}}

const server=http.createServer(async(req,res)=>{try{let u=new URL(req.url,'http://localhost');if(u.pathname==='/api/state'&&req.method==='GET'){let st=load();st.gmail={connected:!!oauth().refresh_token,configured:!!(GCLIENT&&GSECRET)};return json(res,200,st)}
if(u.pathname==='/api/gmail/status'&&req.method==='GET')return json(res,200,{connected:!!oauth().refresh_token,configured:!!(GCLIENT&&GSECRET),redirectUri:REDIRECT});
if(u.pathname==='/api/gmail/connect'&&req.method==='GET'){if(!GCLIENT||!GSECRET)return json(res,400,{error:'missing_google_oauth_config',message:'أضف GOOGLE_CLIENT_ID و GOOGLE_CLIENT_SECRET أولاً.'});let state=crypto.randomBytes(18).toString('hex');saveOauth({...oauth(),state});let q=new URLSearchParams({client_id:GCLIENT,redirect_uri:REDIRECT,response_type:'code',scope:'https://www.googleapis.com/auth/gmail.modify https://www.googleapis.com/auth/gmail.send',access_type:'offline',prompt:'consent',state});res.writeHead(302,{Location:'https://accounts.google.com/o/oauth2/v2/auth?'+q});return res.end()}
if(u.pathname==='/api/gmail/callback'&&req.method==='GET'){let o=oauth();if(!u.searchParams.get('code')||u.searchParams.get('state')!==o.state)return json(res,400,{error:'invalid_oauth_state'});let t=await formPost('https://oauth2.googleapis.com/token',{code:u.searchParams.get('code'),client_id:GCLIENT,client_secret:GSECRET,redirect_uri:REDIRECT,grant_type:'authorization_code'});saveOauth({...t,expires_at:Date.now()+t.expires_in*1000});res.writeHead(302,{Location:'/#agent'});return res.end()}
if(u.pathname==='/api/gmail/disconnect'&&req.method==='POST'){if(fs.existsSync(OAUTH))fs.unlinkSync(OAUTH);return json(res,200,{ok:true})}
if(u.pathname==='/api/gmail/sync'&&req.method==='POST')return json(res,200,await syncGmail());
if(u.pathname==='/api/requests'&&req.method==='POST'){let st=load(),b=await body(req),x={id:'REQ-'+String(Date.now()).slice(-6),title:b.title||'طلب مشتريات جديد',product:b.product||'',specifications:b.specifications||'',quantity:b.quantity||'',deliveryCountry:b.deliveryCountry||'',targetMarkets:b.targetMarkets||'',currency:b.currency||'USD',incoterm:b.incoterm||'FOB',neededBy:b.neededBy||'',notes:b.notes||'',status:'جديد',createdAt:new Date().toISOString()};st.requests=st.requests||[];st.marketScans=st.marketScans||[];st.requests.unshift(x);st.activity.unshift({time:new Date().toISOString(),type:'request',text:'إنشاء '+x.id});save(st);return json(res,201,x)}
let mm=u.pathname.match(/^\\/api\\/requests\\/([^/]+)\\/market-scan$/);if(mm&&req.method==='POST'){let st=load(),b=await body(req),x=(st.requests||[]).find(x=>x.id===mm[1]);if(!x)return json(res,404,{error:'request_not_found'});let scan=await marketScan(st,{...x,sourceObservations:b.sourceObservations||[]});st.marketScans=st.marketScans||[];st.marketScans.unshift(scan);x.marketScanId=scan.id;x.marketStatus='completed';st.activity.unshift({time:new Date().toISOString(),type:'market_scan',text:'Market Intelligence '+x.id+' — '+scan.sourceCount+' sources'});save(st);return json(res,200,scan)}
if(u.pathname==='/api/market-scans'&&req.method==='GET'){let st=load();return json(res,200,st.marketScans||[])}
let sm=u.pathname.match(/^\/api\/suppliers\/([^/]+)$/);if(sm&&req.method==='PATCH'){let st=load(),b=await body(req),x=st.suppliers.find(x=>x.id===sm[1]);if(!x)return json(res,404,{error:'not_found'});Object.assign(x,b);save(st);return json(res,200,x)}
let am=u.pathname.match(/^\/api\/approvals\/([^/]+)$/);if(am&&req.method==='PATCH'){let st=load(),b=await body(req),x=st.approvals.find(x=>x.id===am[1]);if(!x)return json(res,404,{error:'not_found'});x.status=b.status||x.status;x.updatedAt=new Date().toISOString();save(st);return json(res,200,x)}
if(u.pathname==='/api/settings'&&req.method==='PATCH'){let st=load(),b=await body(req);st.settings={...st.settings,...b};save(st);return json(res,200,st.settings)}
if(u.pathname==='/api/quotes'&&req.method==='POST'){let st=load(),b=await body(req),x={id:'Q-'+Date.now(),...b,createdAt:new Date().toISOString()};st.quotes.unshift(x);save(st);return json(res,201,x)}
if(u.pathname==='/api/agent/run'&&req.method==='POST'){let st=load(),b=await body(req);if(b.action==='followup'&&st.settings?.dryRun)return json(res,409,{error:'dry_run_enabled',message:'وضع الحماية مفعل: لا يسمح بإرسال متابعة جماعية فعلية.'});if(b.action==='followup'&&st.settings?.requirePerMessageApproval)return json(res,409,{error:'per_message_approval_required',message:'يلزم اعتماد كل رسالة ومستلم بشكل منفصل قبل الإرسال.'});if(b.action==='followup'&&!gate(st,'followup'))return json(res,409,{error:'approval_required',message:'تحتاج موافقة قبل الإرسال'});if(b.action==='followup'){let targets=st.suppliers.filter(s=>!['رد','تم الرد — ننتظر العرض'].includes(s.status)&&!s.excluded&&s.email);let sent=[];for(let s of targets){await sendMail(s.email,'Follow-up: RFQ-001 – Cold Storage Project, Sana’a','Dear '+s.name+',\n\nThis is a follow-up regarding RFQ-001 for our cold storage project in Sana’a, Yemen. Please send your technical and commercial quotation, including cooling load, equipment brands/models, daily pull-down capacity, 24h power consumption, panel specifications, FOB price/port, CBM/gross weight, lead time, warranty and payment terms.\n\nBest regards,\nAlharir shipping and export');sent.push(s.name)}st.activity.unshift({time:new Date().toISOString(),type:'agent',text:'تم إرسال متابعة إلى '+sent.length+' مورد'});save(st);return json(res,200,{ok:true,sent})}st.activity.unshift({time:new Date().toISOString(),type:'agent',text:'تشغيل الوكيل: '+(b.action||'analyze')});save(st);return json(res,200,{ok:true,action:b.action||'analyze'})}
let file=u.pathname==='/'?'index.html':u.pathname.replace(/^\//,'');let fp=path.join(PUB,file);if(fp.startsWith(PUB)&&fs.existsSync(fp)){let ext=path.extname(fp);res.writeHead(200,{'Content-Type':ext==='.html'?'text/html; charset=utf-8':ext==='.js'?'text/javascript':'text/plain'});return fs.createReadStream(fp).pipe(res)}res.writeHead(404);res.end('Not found')
}catch(e){json(res,500,{error:e.message})}});server.listen(process.env.PORT||8787,()=>console.log('Procurement V2: http://localhost:'+(process.env.PORT||8787)));